gpu_configurations:


 2:
  equal:
    prefill:
      gpus: [0]
      tp: 1
      pp: 1
    decode:
      gpus: [1]
      tp: 1
      pp: 1
 
 4: 
  more_prefill:
    prefill:
      gpus: [0,1]
      tp: 2
      pp: 1
    decode:
      gpus: [2]
      tp: 1
      pp: 1
  more_decode:
    prefill:
      gpus: [0]
      tp: 1
      pp: 1
    decode:
      gpus: [1,2]
      tp: 2
      pp: 1

 8:
    more_decode:
      prefill:
        gpus: [0,1]
        tp: 2
        pp: 1
      decode:
        gpus: [2,3,4,5]
        tp: 4
        pp: 1
